AIOps data quality checker
IBM/cp4mcm-samples pull request #19
Opened 2020-09-21 18:31 UTC by maxhwchang

Signed-off-by: Hau-wen Chang <changha@us.ibm.com>

The PR is to comply with the opensource for the AIOps log data quality checker.

2020-09-24 20:22 UTC, neil-boyette-ibm requested changes
Once you address the changes, I'll approve

2020-09-24 20:22 UTC, neil-boyette-ibm commented on aiops-log-data-quality-checker/CONTRIBUTING.md
> +If you would like to implement a new feature, please [raise an issue](https://github.com/ibm/aiops-log-data-checker/issues)
Please update to this repo.

2020-09-24 20:22 UTC, neil-boyette-ibm commented on aiops-log-data-quality-checker/CONTRIBUTING.md
> +If you would like to fix a bug, please [raise an issue](https://github.com/ibm/aiops-log-data-checker/issues) before sending a
Please update to this repo

2020-09-24 20:22 UTC, neil-boyette-ibm commented on aiops-log-data-quality-checker/CONTRIBUTING.md
> +Please feel free to connect with us on our [Slack channel](https://ibm-analytics.slack.com/archives/CL3DQ80EN).
This is an internal slack channel. Let's replace it w/ a link to the maintainers md file.

2020-09-24 20:22 UTC, neil-boyette-ibm commented on aiops-log-data-quality-checker/README.md
> +**Note:** Make sure you update the [Changelog](CHANGELOG.md) each time you add, remove, or update sample files.
Please add a reference to the contributing md file for more details.

2020-09-24 20:22 UTC, neil-boyette-ibm commented on aiops-log-data-quality-checker/logs_data_checker_tests/data/normalized_example.json
> +{"message":"invoking [applyModel] WorkspaceId = 1b69b204-5432-496f-8e61-da7e4b037730","timestamp":1578669135680,"instance_id":"nlu","features":[],"meta_features":[{"type":"WindowMeta","obj_value":{"s
Please replace w/ generic example file

2020-09-24 20:22 UTC, neil-boyette-ibm commented on aiops-log-data-quality-checker/logs_data_checker_tests/data/test_line.json
> +  "instance_id": "nlu",
Please replace w/ generic test file

2020-09-24 20:22 UTC, neil-boyette-ibm commented on aiops-log-data-quality-checker/logs_data_checker_tests/data/test_main_bad.input
> +{"application_group_id": "1", "application_id": "1", "application": "node1", "timestamp": 1591039175920.0, "utc_timestamp": "2020-06-01T19:19:35.920000Z", "type": "log", "instance_id": "node1", "mess
Please replace w/ generic example file

2020-09-24 20:22 UTC, neil-boyette-ibm commented on aiops-log-data-quality-checker/logs_data_checker_tests/data/test_main_good.input
> +{"application_id": "def456", "entities": {"pod": "pmp026-nlu-5d77786646-676q6", "_cluster": "ld60", "container": "nlu"}, "features": [], "instance_id": "nlu", "level": 1, "message": "invoking [applyM
Please replace w/ generic example file

2020-09-24 23:39 UTC, maxhwchang commented on aiops-log-data-quality-checker/README.md
> +**Note:** Make sure you update the [Changelog](CHANGELOG.md) each time you add, remove, or update sample files.
done!

2020-09-24 23:42 UTC, maxhwchang commented on aiops-log-data-quality-checker/CONTRIBUTING.md
> +If you would like to implement a new feature, please [raise an issue](https://github.com/ibm/aiops-log-data-checker/issues)
done

2020-09-24 23:43 UTC, maxhwchang commented on aiops-log-data-quality-checker/CONTRIBUTING.md
> +Please feel free to connect with us on our [Slack channel](https://ibm-analytics.slack.com/archives/CL3DQ80EN).
done!

2020-09-24 23:43 UTC, maxhwchang commented on aiops-log-data-quality-checker/logs_data_checker_tests/data/normalized_example.json
> +{"message":"invoking [applyModel] WorkspaceId = 1b69b204-5432-496f-8e61-da7e4b037730","timestamp":1578669135680,"instance_id":"nlu","features":[],"meta_features":[{"type":"WindowMeta","obj_value":{"s
done

2020-09-24 23:43 UTC, maxhwchang commented on aiops-log-data-quality-checker/logs_data_checker_tests/data/test_main_bad.input
> +{"application_group_id": "1", "application_id": "1", "application": "node1", "timestamp": 1591039175920.0, "utc_timestamp": "2020-06-01T19:19:35.920000Z", "type": "log", "instance_id": "node1", "mess
done

2020-09-24 23:43 UTC, maxhwchang commented on aiops-log-data-quality-checker/logs_data_checker_tests/data/test_line.json
> +  "instance_id": "nlu",
done

2020-09-24 23:44 UTC, maxhwchang commented on aiops-log-data-quality-checker/README.md
> +**Note:** Make sure you update the [Changelog](CHANGELOG.md) each time you add, remove, or update sample files.
done

2020-09-24 23:44 UTC, maxhwchang commented on aiops-log-data-quality-checker/logs_data_checker_tests/data/test_main_good.input
> +{"application_id": "def456", "entities": {"pod": "pmp026-nlu-5d77786646-676q6", "_cluster": "ld60", "container": "nlu"}, "features": [], "instance_id": "nlu", "level": 1, "message": "invoking [applyM
done

2020-09-24 23:44 UTC, maxhwchang commented on aiops-log-data-quality-checker/CONTRIBUTING.md
> +If you would like to fix a bug, please [raise an issue](https://github.com/ibm/aiops-log-data-checker/issues) before sending a
done!

2020-09-25 00:04 UTC, neil-boyette-ibm approved these changes
LGTM - Thanks Max !

2020-09-25 00:57 UTC, merged